---
channels:
  - conda-forge
dependencies:
  - cython  # only needed for pyquante2
  - h5py
  - libint=2.9.0=*_4
  - pip
  - pip-tools
  - psi4
  - pytest-cov
  - pytest-shutil
  - pytest-xdist
  - python=3.11
