---
channels:
  - conda-forge/label/libint_dev
  - conda-forge
dependencies:
  - cmake  # needed for pyscf but not on earlier Python versions
  - cython  # only needed for pyquante2
  - h5py
  - openbabel
  - pip
  - pip-tools
  - psi4
  - pytest-cov
  - pytest-shutil
  - pytest-xdist
  - python=3.13
