---
channels:
  - psi4
  - conda-forge/label/libint_dev
  - conda-forge
  - defaults
dependencies:
  - cython  # only needed for pyquante2
  - h5py=3.1
  - openbabel
  - pip
  - psi4
  - pytest-cov
  - pytest-shutil
  - python=3.8
  - pip:
      - pyscf<2.3
      - qc-iodata
  # https://github.com/MolSSI/QCElemental/issues/312
  - pydantic<2
